# site settings
title: To Bhaito
subtitle: with love, from old sis Debbie
email: debarghya.kar@gmail.com
description: Welcome to the world of Debarghya!!
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: http://debanjanakar.github.io/forty-jekyll-theme/
author:
street_address: 
city: Kolkata
state: West Bengal
zip_code: 
country: India
phone: +91 8820069595

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url: https://www.facebook.com/profile.php?id=100000730968363
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/debarghya-kar-056962189/?originalSubdomain=in
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
